log_directory: ./logs
print_config: true
mode: depthnorm
training_stage: train
split_save_dir: ''
num_workers: 1
val_check_interval: 10
val_plot_interval: 1
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu
  log_every_n_steps: 2
  overfit_batches: 0
depth_norm_config:
  resume_from_checkpoint: /Users/peter/git/cysto_depth/logs/depthnorm/lightning_logs/version_17/checkpoints/epoch=3-step=2683.ckpt
  encoder:
    load_imagenet_weights: True
    backbone: resnet18
  accumulate_grad_batches: 1
  L_loss: L1
  use_critic: true
  critic_config:
    single_out: true
    use_sigmoid: false
    single_out_reduction: dense
  use_discriminator: true
  discriminator_config:
    single_out: false
    single_out_reduction: max
  generator_lr: 5e-4
  discriminator_lr: 5e-5
  critic_lr: 5e-5
  add_noise: false
  max_epochs: 300
  batch_size: 4
  data_roles:
    - color_0
    - color_1
    - depth_0
    - depth_1
    - normals_0
    - normals_1
  data_directories:
    -
      - /Users/peter/isys/2023_01_29/color/bladder_wall
    -
      - /Users/peter/isys/2023_01_29/color/bland_bladder_wall
    -
      - /Users/peter/isys/2023_01_29/depth/bladder_wall
    -
      - /Users/peter/isys/2023_01_29/depth/bland_bladder_wall
    -
      - /Users/peter/isys/2023_01_29/normals/bladder_wall
    -
      - /Users/peter/isys/2023_01_29/normals/bland_bladder_wall
  training_split: {'train': .98, 'validate': 0.01, 'test': .01}