log_directory: ./logs
print_config: true
mode: depthnorm
training_stage: train
split_save_dir: ''
num_workers: 0
val_check_interval: 30
val_plot_interval: 1
image_size: 64
pin_dataloader_memory: true
trainer_config:
  gpus: []
  strategy: null
  accelerator: mps
  log_every_n_steps: 2
  overfit_batches: 0
depth_norm_config:
#  resume_from_checkpoint: /Users/peter/git/cysto_depth/logs/depthnorm/lightning_logs/version_44/checkpoints/epoch=43-step=9848.ckpt
  encoder:
    load_imagenet_weights: True
    backbone: resnet18
  accumulate_grad_batches: 1
  L_loss: ''
  use_critic: false
  use_discriminator: true
  discriminator_loss: cross_entropy_R1
  hyper_volume_slack: 1.2
  discriminator_ensemble_size: 3
  discriminator_config:
    single_out: false
    output_activation: 'sigmoid'
    single_out_reduction: sum
    add_coordinates: true
  generator_lr: 2e-6
  discriminator_lr: 2e-6
  discriminator_generated_confidence: 0.0
  discriminator_original_confidence: 1.0
  add_noise: false
  max_epochs: 300
  batch_size: 8
  data_roles:
    - color_0
    - color_1
    - depth_0
    - depth_1
    - normals_0
    - normals_1
  data_directories:
    -
      - /Users/peter/isys/2023_01_29/color/bladder_wall
    -
      - /Users/peter/isys/2023_01_29/color/bland_bladder_wall
    -
      - /Users/peter/isys/2023_01_29/depth/bladder_wall
    -
      - /Users/peter/isys/2023_01_29/depth/bland_bladder_wall
    -
      - /Users/peter/isys/2023_01_29/normals/bladder_wall
    -
      - /Users/peter/isys/2023_01_29/normals/bland_bladder_wall
  training_split: {'train': .98, 'validate': 0.01, 'test': .01}
