log_directory: ./logs
predict_normals: true
print_config: true
mode: gan
training_stage: train
split_save_dir: ./splits
num_workers: 1
synthetic_config:
  encoder:
    load_imagenet_weights: True
    backbone: resnet18
    res_layer_norm: instance
  normals_extra_layers: 0
  decoder_calculate_norms: false
  merged_decoder: true
  accumulate_grad_batches: 1
  max_epochs: 300
  batch_size: 4
  data_roles:
    - color
    - depth
    - normals
  data_directories:
    - /Users/peter/isys/2023_01_29/color
    - /Users/peter/isys/2023_01_29/depth
    - /Users/peter/isys/2023_01_29/normals
  training_split: {'train': .8, 'validate': 0.18, 'test': .02}
#  resume_from_checkpoint: ./logs/synthetic/lightning_logs/version_1/epoch=13-step=378.ckpt
gan_config:
  synthetic_base_model: /Users/peter/Desktop/epoch=198-step=10920.ckpt
  encoder:
    backbone: resnet18
    adaptive_gating: true
    residual_learning: true
    res_layer_norm: instance
  use_critic: true
  use_discriminator: true
  generator_lr: 5e-4
  discriminator_lr: 5e-5
  critic_lr: 5e-5
  critic_loss: wasserstein_gp
  wasserstein_critic_updates: 2
  discriminator_loss: cross_entropy
  wasserstein_lambda: 10.0
  freeze_batch_norm: true
  phong_discriminator_factor: 1.0
  batch_size: 4
  accumulate_grad_batches: 1
  warmup_steps: 0
  source_images:
    - /Users/peter/isys/2023_01_29/color
  synth_split: {'train': .8, 'validate': .1, 'test': .1}
  generate_data: False
  videos_folder:
    - /Users/peter/isys/videos
  image_output_folder: ./gan_data
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu
  log_every_n_steps: 2