log_directory: ./logs
predict_normals: true
print_config: true
adaptive_gating: true
mode: gan
training_stage: train
split_save_dir: ./splits
num_workers: 1
synthetic_config:
  backbone: resnet34
  merged_decoder: true
  max_epochs: 300
  normals_extra_layers: 0
  batch_size: 4
  data_roles:
    - color
    - depth
    - normals
  data_directories:
    - /Users/peter/isys/2023_01_29/color
    - /Users/peter/isys/2023_01_29/depth
    - /Users/peter/isys/2023_01_29/normals
  training_split: {'train': .8, 'validate': 0.18, 'test': .02}
#  resume_from_checkpoint: ./logs/synthetic/lightning_logs/version_1/epoch=13-step=378.ckpt
gan_config:
  batch_size: 2
  source_images:
    - /Users/peter/isys/2023_01_29/color
  synthetic_base_model: /Users/peter/Desktop/epoch=198-step=10920.ckpt
  synth_split: {'train': .8, 'validate': .1, 'test': .1}
  generate_data: False
  videos_folder:
    - /Users/peter/isys/videos
  image_output_folder: ./gan_data
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu
  log_every_n_steps: 2