log_directory: ./logs
predict_normals: true
print_config: true
mode: synthetic
training_stage: train
split_save_dir: ./splits
num_workers: 0
image_size: 256
synthetic_config:
  balance_batchnorm_with_real: true
  data_roles:
    - color
    - depth
    - normals
  data_directories:
    - /Users/peter/isys/2023_01_29/color
    - /Users/peter/isys/2023_01_29/depth
    - /Users/peter/isys/2023_01_29/normals
  training_split: {'train': .8, 'validate': 0.18, 'test': .02}
  # resume_from_checkpoint: /Users/peter/isys/desktop_dump/synthetic_256.ckpt
gan_config:
  encoder:
    adaptive_gating: true
    residual_learning: true
    res_layer_norm: instance
  use_critic: false
  use_discriminator: true
  use_feature_level: true
  generator_lr: 5e-4
  discriminator_lr: 5e-5
  discriminator_loss: cross_entropy_R1
  freeze_batch_norm: true
  phong_discriminator_factor: 1.0
  batch_size: 4
  accumulate_grad_batches: 1
  warmup_steps: 0
  source_images:
    - /Users/peter/isys/2023_01_29/color
  synth_split: {'train': .8, 'validate': .1, 'test': .1}
  generate_data: False
  videos_folder:
    - /Users/peter/isys/videos
  image_output_folder: ./gan_data
  hyper_volume_slack: 1.2
  discriminator_ensemble_size: 3
trainer_config:
  gpus: []
  strategy: null
  accelerator: cpu
  log_every_n_steps: 2